### ISSUE TITLE
build on a Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [MaKiPL/OpenVIII-monogame#175]
can the be built on a Pi4 or is this project only on x86.

and this is a very cool project BTW. FF8 is my Fav

**Comment by Sebanisu** [comment]
It runs on linux but the current program. If you can get to compile it should run on your pi. Though it might run out of memory. You'd need like arm versions of the libraries. It might take some playing around to get it to work.

Though this not done. So it mostly lets you test out the menu, world map, and battle modules. It's far from the whole game right now. 

The code is a bit memory hungry mostly my fault. I was trying to preload a lot of things into memory. So I'd fill up the ram real fast. I'm trying to do better in my c++ port but it's slow going. I plan to back port things to this if I whenever get caught up. :)

**Comment by Exarkuniv** [comment]
thank you for getting back to me. might be something i would play around to see if i can get working just to do so. once i get better at hunting down things when errors pop up
