### ISSUE TITLE
question cdda pc2000

### ISSUE THREAD

**Issue by shikulja** [MaKiPL/OpenVIII-monogame#188]
Eyes on me is on 3cd disc as cdda track, lots of nocd for pc2000, didn't need this track. The question was whether this affected the music in the game, and is it necessary for openviii?

**Comment by Sebanisu** [comment]
I believe the music wouldn't play if you didn't have the cd. It's only used in that scene in space on disc 3. In steam releases it was replaced with a wav file of the song. I guess it's possible for your iso or nocd to give the game different music. I never tried a nocd mod myself to find out.

Personally I'd rather take the steam approche and play audio from some file wav, ogg, w/e. CDDA might be harder to do cross platform as most people don't have cd drives anymore. You get boo'ed off stackoverflow if you ask about cds.
